FROM mysql:8.0.29

ENV MYSQL_USER=ian
ENV MYSQL_PASSWORD=ian1234
ENV MYSQL_ROOT_PASSWORD=root1234
ENV MYSQL_DATABASE=iandb

CMD ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]